export default [
    {
        "_id": "CS5610",
        "name": "Web Development",
        "number": "CS5610",
        "startDate": "2025-09-01T09:00:00-04:00",
        "endDate": "2025-12-15T18:00:00-04:00",
        "department": "Computer Science",
        "credits": 4,
        "instructor": "Jose Annunziato",
        "description": "Explores the design and implementation of Web applications and services. Topics include HTML, CSS, JavaScript, HTTP, Web APIs, Web frameworks, databases, authentication, and security. Fall 2025 Semester Full Term.",
        "image": "/images/cs5610.png",
        "color": "#e35d86"
    },
    {
        "_id": "CS5520",
        "name": "Mobile Application Development",
        "number": "CS5520",
        "startDate": "2025-09-01T09:00:00-04:00",
        "endDate": "2025-12-15T18:00:00-04:00",
        "department": "Computer Science",
        "credits": 4,
        "instructor": "Sakib Miazi",
        "description": "Covers the design and implementation of mobile applications for iOS using Swift and Xcode. Topics include UI design, navigation controllers, table views, HTTP connections, JSON parsing, Firebase authentication, and database integration. Fall 2025 Semester Full Term.",
        "image": "/images/cs5520.png",
        "color": "#FE4E00"
    },
    {
        "_id": "CS5008",
        "name": "Data Structures and Algorithms",
        "number": "CS5008",
        "startDate": "2025-01-08T10:00:00-04:00",
        "endDate": "2025-04-30T17:00:00-04:00",
        "department": "Computer Science",
        "credits": 4,
        "instructor": "Prof Faculty",
        "description": "Covers fundamental data structures and algorithms in C. Topics include arrays, linked lists, stacks, queues, trees, graphs, sorting, searching, and algorithm analysis. Spring 2025 Semester Full Term.",
        "image": "/images/cs5008.png",
        "color": "#FF579F"
    },
    {
        "_id": "CS5800",
        "name": "Algorithms",
        "number": "CS5800",
        "startDate": "2025-05-06T09:00:00-04:00",
        "endDate": "2025-08-15T17:00:00-04:00",
        "department": "Computer Science",
        "credits": 4,
        "instructor": "Drew van der Poel",
        "description": "Studies the design and analysis of algorithms. Topics include divide-and-conquer, dynamic programming, greedy algorithms, graph algorithms, NP-completeness, and approximation algorithms. Summer Full 2025 Semester.",
        "image": "/images/cs5800.png",
        "color": "#7b3fb9"
    },
    {
        "_id": "CS5001",
        "name": "Intensive Foundations of Computer Science",
        "number": "CS5001",
        "startDate": "2024-09-01T09:00:00-04:00",
        "endDate": "2024-12-15T18:00:00-04:00",
        "department": "Computer Science",
        "credits": 4,
        "instructor": "Keith Bagley",
        "description": "Introduces the fundamental concepts of computer science and programming using Python. Topics include variables, functions, conditionals, loops, lists, strings, files, dictionaries, recursion, and algorithm analysis. Designed for students with no prior programming experience. Fall 2024 Semester Full Term.",
        "image": "/images/cs5001.png",
        "color": "#5D2E46"
    },
    {
        "_id": "CS5002",
        "name": "Discrete Structures",
        "number": "CS5002",
        "startDate": "2024-09-01T09:00:00-04:00",
        "endDate": "2024-12-15T18:00:00-04:00",
        "department": "Computer Science",
        "credits": 4,
        "instructor": "Amor Tijani",
        "description": "Introduces the mathematical structures and methods that form the foundation of computer science. Topics include sets, functions, relations, sequences, induction, recursion, proof techniques, counting, graphs, and trees. Uses zyBooks interactive textbook. Fall 2024 Semester Full Term.",
        "image": "/images/cs5002.png",
        "color": "#6457A6"
    },
    {
        "_id": "CS5004",
        "name": "Object-Oriented Design",
        "number": "CS5004",
        "startDate": "2025-01-08T10:00:00-04:00",
        "endDate": "2025-04-30T17:00:00-04:00",
        "department": "Computer Science",
        "credits": 4,
        "instructor": "Keith Bagley",
        "description": "Introduces object-oriented design and programming using Java. Topics include classes, objects, methods, inheritance, exceptions, interfaces, polymorphism, design patterns, and software development practices. Spring 2025 Semester Full Term.",
        "image": "/images/cs5004.png",
        "color": "#2E86AB"
    },
    {
        "_id": "RS4550",
        "name": "Rocket Propulsion",
        "number": "RS4550",
        "startDate": "2023-01-10T10:00:00-04:00",
        "endDate": "2023-05-15T17:00:00-04:00",
        "department": "Rocket Science",
        "credits": 4,
        "instructor": "Richard Feynman",
        "description": "This course provides an in-depth study of the fundamentals of rocket propulsion, covering the basics of rocket engines, propellants, and the practical applications of rocket technology. Students will explore the history of rocketry, the physics of rocket motion, and the design and analysis of various types of rocket engines.",
        "image": "/images/RS4550.png",
        "color": "#dc3545"
    },
    {
        "_id": "RS4560",
        "name": "Aerodynamics",
        "number": "RS4560",
        "startDate": "2023-01-10T10:00:00-04:00",
        "endDate": "2023-05-15T17:00:00-04:00",
        "department": "Rocket Science",
        "credits": 3,
        "instructor": "Katherine Johnson",
        "description": "This course offers a comprehensive exploration of aerodynamics, focusing on the principles and applications of airflow and pressure distribution around objects. Students will delve into topics such as lift, drag, and airflow patterns, gaining a deep understanding of how these factors affect the design and performance of aircraft and other vehicles.",
        "image": "/images/rs4560.png",
        "color": "#0dcaf0"
    },
    {
        "_id": "RS4570",
        "name": "Spacecraft Design",
        "number": "RS4570",
        "startDate": "2023-01-10T10:00:00-04:00",
        "endDate": "2023-05-15T17:00:00-04:00",
        "department": "Rocket Science",
        "credits": 4,
        "instructor": "Werner von Braun",
        "description": "This course delves into the principles and practices of spacecraft design, offering students a detailed understanding of the engineering and technology behind spacecraft systems. Topics include spacecraft structure, propulsion, thermal control, and life support systems, with a focus on the design and analysis of spacecraft for various missions.",
        "image": "/images/rs4570.png",
        "color": "#6c757d"
    }
];